version: "3.9"

services:

  api:
    build: ./server
    image: covisourceapi
    container_name: covisource-api
    volumes:
      - ./server:/api
    ports:
      - 4000:4000
    links:
      - database
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/covisourcetestdb

  react:
    build: ./client
    image: covisourceclient
    container_name: covisource-client
    volumes:
      - ./client:/client
    ports:
      - 3000:3000
    environment:
      mode: dev
    env_file:
      - .env.client.dev

  redis:
    image: redis
    container_name: covisource-redis
    ports:
      - 6379:6379

  database:
    container_name: covisource-database
    image: postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  database-data:
