name: Frontend CI/CD

on:
  push:
    branches: [ dev, main, frontend-dev ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: cd client && yarn install

    - name: Run the tests and generate coverage report
      run: cd client && yarn test -- --coverage --passWithNoTests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Build
      run: cd client && yarn run build
